### ISSUE TITLE
Update SideEffect component

### ISSUE THREAD

**Issue by palvarez89** [etcaterva/eas-frontend#148] opened 2020-01-12 18:09 UTC
Probably not a big issue, but I can see the following warning when starting the frontend:

```
Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move code from componentWillMount to componentDidMount (preferred in most cases) or the constructor.

Please update the following components: SideEffect(NullComponent)
```

**Comment by dnaranjo89** [comment] 2020-01-12 21:29
Do you mean with you run `npm start`?

**Comment by palvarez89** [comment] 2020-01-13 11:04
I think so, I mean, this is coming out in the docker logs after starting it.

**Comment by dnaranjo89** [comment] 2020-01-19 17:49
I cannot reproduce it locally. Can you share the full log?

**Comment by palvarez89** [comment] 2020-01-20 12:05
That was literally the full log I saw in our dev host.

```
$ sudo docker logs --follow cd4aedd7055d

> echaloasuerte@0.1.0 start /usr/src/app
> node ./server/index.js

b06b4881452d6b9479bbe171e26fba11d3c20906
[BABEL] Note: The code generator has deoptimised the styling of /usr/src/app/node_modules/react-dom/cjs/react-dom.development.js as it exceeds the max of 500KB.
{"message":"App started","level":"info","timestamp":"2020-01-20 12:02:05"}
App listening on port 80!
Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move code from componentWillMount to componentDidMount (preferred in most cases) or the constructor.

Please update the following components: SideEffect(NullComponent)

```

**Comment by dnaranjo89** [comment] 2020-03-01 18:06
That's an issue from `react-helmet`. It has been solved already but need to wait until the stable version 6 is released
https://github.com/bbc/simorgh/issues/3893#issuecomment-584069340

**Comment by mariocj89** [comment] 2021-02-04 14:51
Closing as there seems to be no action to be taken here. Is that right? We removed that dependency on https://github.com/etcaterva/eas-frontend/commit/2fd2a80841234e1ab5aefa48735f0883da5f561e

**Closed by mariocj89** 2021-02-04 14:51 UTC
